### ISSUE TITLE
Default kde notifications missing

### ISSUE THREAD

**Issue by Prn-Ice** [Intika-Linux-Plasmoid/plasmoid-notifications-full#3]
Just got the update to 5.16 and wanted to try the new notification system but after uninstalling the plasmoid I no longer get notifications.

![2019-07-06_02-23](https://user-images.githubusercontent.com/48252841/60749678-1a32ef80-9f95-11e9-86bc-bdf9fd5ebe33.png)

And my system tray displays only full notifications.
Please help.

**Comment by Prn-Ice** [comment]
Just needed to delete it from plasmoids folder

**Comment by intika** [comment]
what's the changes on 5.16 notification system i did not tried it out yet ?
